---
title: "simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(npmi)


# Create data
features <- c("WEATHER", "POLITICS", "COUNTER","RACISM")

threads <- tibble(feature_source=features,feature_target=features) %>% 
  complete(feature_source,feature_target) %>% 
  mutate(n = case_when(
    (feature_source == "COUNTER") & (feature_target == "RACISM") ~ list(1:1),
    (feature_source == "RACISM") & (feature_target == "COUNTER") ~ list(1:1),
    TRUE ~ list(1:10)
  )) %>% 
  unnest(n) %>% 
  filter(feature_source != feature_target)  %>% 
  mutate(item = row_number()) %>% 
  pivot_longer(c(feature_source,feature_target),names_to="name",values_to="feature") %>% 
  select(-name)

  
```

```{r}

# Calculate p values for each combination
pairs <- threads %>% 
  get_cooccurrence() %>% 
  as_tibble()

# Plot matrix
pairs %>% 
  select(source=feature_source,target=feature_target,value=n) %>% 
  matrixmap() +
  theme_bw(base_size=10)

```

```{r}
# Resample cooccurrence and calculate NPMI
# Be patient...simulates 1000 random worlds for the baseline probability
pairs_resampled <- threads %>%
  resample_cooccurrence(trials=100)

pairs_resampled$pairs %>% 
  filter(sig == T) %>% 
  select(source=feature_source,target=feature_target,value=npmi,value.max=1,value.min=-1) %>% 
  matrixmap() +
  theme_bw(base_size=10)

```

